# jugadores_data.py
# Generado a partir de SQUAD_REGISTRY de index.bundle.js

jugadores_por_equipo = {'Real Madrid': [{'numero': '1', 'nombre': 'Courtois', 'posicion': 'portero', 'poder': 89},
                 {'numero': '13', 'nombre': 'Lunin', 'posicion': 'portero', 'poder': 80},
                 {'numero': '26', 'nombre': 'Fran González', 'posicion': 'portero', 'poder': 64},
                 {'numero': '25', 'nombre': 'Mestre', 'posicion': 'portero', 'poder': 60},
                 {'numero': '12', 'nombre': 'Trent', 'posicion': 'defensa', 'poder': 86},
                 {'numero': '2', 'nombre': 'Carvajal', 'posicion': 'defensa', 'poder': 85},
                 {'numero': '22', 'nombre': 'Rüdiger', 'posicion': 'defensa', 'poder': 85},
                 {'numero': '3', 'nombre': 'Militão', 'posicion': 'defensa', 'poder': 84},
                 {'numero': '24', 'nombre': 'Huijsen', 'posicion': 'defensa', 'poder': 82},
                 {'numero': '4', 'nombre': 'Alaba', 'posicion': 'defensa', 'poder': 80},
                 {'numero': '23', 'nombre': 'Mendy', 'posicion': 'defensa', 'poder': 81},
                 {'numero': '18', 'nombre': 'Carreras', 'posicion': 'defensa', 'poder': 80},
                 {'numero': '15', 'nombre': 'Asencio', 'posicion': 'defensa', 'poder': 78},
                 {'numero': '20', 'nombre': 'Fran García', 'posicion': 'defensa', 'poder': 77},
                 {'numero': '27', 'nombre': 'Aguado', 'posicion': 'defensa', 'poder': 59},
                 {'numero': '5', 'nombre': 'Bellingham', 'posicion': 'medio', 'poder': 89},
                 {'numero': '8', 'nombre': 'Valverde', 'posicion': 'medio', 'poder': 88},
                 {'numero': '14', 'nombre': 'Tchouaméni', 'posicion': 'medio', 'poder': 84},
                 {'numero': '6', 'nombre': 'Camavinga', 'posicion': 'medio', 'poder': 82},
                 {'numero': '10', 'nombre': 'Arda Güler', 'posicion': 'medio', 'poder': 82},
                 {'numero': '21', 'nombre': 'Brahim', 'posicion': 'medio', 'poder': 81},
                 {'numero': '19', 'nombre': 'Ceballos', 'posicion': 'medio', 'poder': 80},
                 {'numero': '16', 'nombre': 'Gonzalo', 'posicion': 'medio', 'poder': 73},
                 {'numero': '30', 'nombre': 'Mastantuono', 'posicion': 'medio', 'poder': 77},
                 {'numero': '45', 'nombre': 'Pitarch', 'posicion': 'medio', 'poder': 60},
                 {'numero': '28', 'nombre': 'Cestero', 'posicion': 'medio', 'poder': 63},
                 {'numero': '9', 'nombre': 'Mbappé', 'posicion': 'delantero', 'poder': 91},
                 {'numero': '7', 'nombre': 'Vinicius', 'posicion': 'delantero', 'poder': 89},
                 {'numero': '11', 'nombre': 'Rodrygo', 'posicion': 'delantero', 'poder': 84}],
 'FC Barcelona': [{'numero': '1', 'nombre': 'Joan García', 'posicion': 'portero', 'poder': 85},
                  {'numero': '13', 'nombre': 'Szczęsny', 'posicion': 'portero', 'poder': 83},
                  {'numero': '25', 'nombre': 'Kochen', 'posicion': 'portero', 'poder': 61},
                  {'numero': '23', 'nombre': 'Koundé', 'posicion': 'defensa', 'poder': 86},
                  {'numero': '2', 'nombre': 'Cancelo', 'posicion': 'defensa', 'poder': 84},
                  {'numero': '3', 'nombre': 'Balde', 'posicion': 'defensa', 'poder': 83},
                  {'numero': '24', 'nombre': 'Eric García', 'posicion': 'defensa', 'poder': 83},
                  {'numero': '4', 'nombre': 'Araújo', 'posicion': 'defensa', 'poder': 82},
                  {'numero': '5', 'nombre': 'Cubarsí', 'posicion': 'defensa', 'poder': 82},
                  {'numero': '18', 'nombre': 'G. Martín', 'posicion': 'defensa', 'poder': 76},
                  {'numero': '15', 'nombre': 'Christensen', 'posicion': 'defensa', 'poder': 80},
                  {'numero': '8', 'nombre': 'Pedri', 'posicion': 'medio', 'poder': 90},
                  {'numero': '21', 'nombre': 'F. de Jong', 'posicion': 'medio', 'poder': 87},
                  {'numero': '20', 'nombre': 'Dani Olmo', 'posicion': 'medio', 'poder': 84},
                  {'numero': '6', 'nombre': 'Gavi', 'posicion': 'medio', 'poder': 83},
                  {'numero': '16', 'nombre': 'Fermín', 'posicion': 'medio', 'poder': 83},
                  {'numero': '14', 'nombre': 'Rashford', 'posicion': 'medio', 'poder': 81},
                  {'numero': '17', 'nombre': 'Casadó', 'posicion': 'medio', 'poder': 79},
                  {'numero': '22', 'nombre': 'Bernal', 'posicion': 'medio', 'poder': 74},
                  {'numero': '35', 'nombre': 'T. Fernández', 'posicion': 'medio', 'poder': 64},
                  {'numero': '40', 'nombre': 'Jofre', 'posicion': 'medio', 'poder': 61},
                  {'numero': '34', 'nombre': 'G. Fernández', 'posicion': 'medio', 'poder': 60},
                  {'numero': '43', 'nombre': 'Marqués', 'posicion': 'medio', 'poder': 59},
                  {'numero': '10', 'nombre': 'Lamine Yamal', 'posicion': 'delantero', 'poder': 89},
                  {'numero': '11', 'nombre': 'Raphinha', 'posicion': 'delantero', 'poder': 89},
                  {'numero': '9', 'nombre': 'Lewandowski', 'posicion': 'delantero', 'poder': 87},
                  {'numero': '7', 'nombre': 'Ferran Torres', 'posicion': 'delantero', 'poder': 84},
                  {'numero': '28', 'nombre': 'Bardghji', 'posicion': 'delantero', 'poder': 74}],
 'Athletic Club': [{'numero': '1', 'nombre': 'Unai Simón', 'posicion': 'portero', 'poder': 84},
                   {'numero': '13', 'nombre': 'Padilla', 'posicion': 'portero', 'poder': 69},
                   {'numero': '25', 'nombre': 'Manex', 'posicion': 'portero', 'poder': 63},
                   {'numero': '4', 'nombre': 'Laporte', 'posicion': 'defensa', 'poder': 82},
                   {'numero': '5', 'nombre': 'Vivian', 'posicion': 'defensa', 'poder': 83},
                   {'numero': '6', 'nombre': 'Yeray', 'posicion': 'defensa', 'poder': 82},
                   {'numero': '17', 'nombre': 'Berchiche', 'posicion': 'defensa', 'poder': 79},
                   {'numero': '19', 'nombre': 'Gorosabel', 'posicion': 'defensa', 'poder': 76},
                   {'numero': '18', 'nombre': 'Areso', 'posicion': 'defensa', 'poder': 77},
                   {'numero': '20', 'nombre': 'Lekue', 'posicion': 'defensa', 'poder': 73},
                   {'numero': '7', 'nombre': 'Paredes', 'posicion': 'defensa', 'poder': 78},
                   {'numero': '27', 'nombre': 'Maroan', 'posicion': 'defensa', 'poder': 73},
                   {'numero': '24', 'nombre': 'A. Hierro', 'posicion': 'defensa', 'poder': 60},
                   {'numero': '21', 'nombre': 'Monreal', 'posicion': 'defensa', 'poder': 70},
                   {'numero': '14', 'nombre': 'Egiluz', 'posicion': 'defensa', 'poder': 70},
                   {'numero': '9', 'nombre': 'Sancet', 'posicion': 'medio', 'poder': 83},
                   {'numero': '22', 'nombre': 'B. Prados', 'posicion': 'medio', 'poder': 78},
                   {'numero': '10', 'nombre': 'Galarreta', 'posicion': 'medio', 'poder': 80},
                   {'numero': '23', 'nombre': 'Jauregizar', 'posicion': 'medio', 'poder': 80},
                   {'numero': '15', 'nombre': 'Vesga', 'posicion': 'medio', 'poder': 73},
                   {'numero': '16', 'nombre': 'U. Gómez', 'posicion': 'medio', 'poder': 73},
                   {'numero': '26', 'nombre': 'N. Serrano', 'posicion': 'medio', 'poder': 70},
                   {'numero': '25', 'nombre': 'Boiro', 'posicion': 'medio', 'poder': 73},
                   {'numero': '11', 'nombre': 'Rego', 'posicion': 'medio', 'poder': 71},
                   {'numero': '29', 'nombre': 'Selton', 'posicion': 'medio', 'poder': 62},
                   {'numero': '11', 'nombre': 'Nico Williams', 'posicion': 'delantero', 'poder': 86},
                   {'numero': '12', 'nombre': 'Iñaki Williams', 'posicion': 'delantero', 'poder': 82},
                   {'numero': '3', 'nombre': 'Berenguer', 'posicion': 'delantero', 'poder': 81},
                   {'numero': '2', 'nombre': 'Guruzeta', 'posicion': 'delantero', 'poder': 78},
                   {'numero': '28', 'nombre': 'Izeta', 'posicion': 'delantero', 'poder': 71}],
 'Atletico Madrid': [{'numero': '1', 'nombre': 'Oblak', 'posicion': 'portero', 'poder': 88},
                     {'numero': '13', 'nombre': 'Musso', 'posicion': 'portero', 'poder': 79},
                     {'numero': '26', 'nombre': 'Esquivel', 'posicion': 'portero', 'poder': 63},
                     {'numero': '3', 'nombre': 'Marcos Llorente', 'posicion': 'defensa', 'poder': 84},
                     {'numero': '2', 'nombre': 'Hancko', 'posicion': 'defensa', 'poder': 83},
                     {'numero': '5', 'nombre': 'Giménez', 'posicion': 'defensa', 'poder': 83},
                     {'numero': '4', 'nombre': 'Le Normand', 'posicion': 'defensa', 'poder': 81},
                     {'numero': '6', 'nombre': 'Lenglet', 'posicion': 'defensa', 'poder': 78},
                     {'numero': '12', 'nombre': 'Pubill', 'posicion': 'defensa', 'poder': 78},
                     {'numero': '20', 'nombre': 'N. Molina', 'posicion': 'defensa', 'poder': 77},
                     {'numero': '23', 'nombre': 'Ruggeri', 'posicion': 'defensa', 'poder': 76},
                     {'numero': '36', 'nombre': 'Kostis', 'posicion': 'defensa', 'poder': 68},
                     {'numero': '7', 'nombre': 'Griezmann', 'posicion': 'medio', 'poder': 84},
                     {'numero': '14', 'nombre': 'P. Barrios', 'posicion': 'medio', 'poder': 83},
                     {'numero': '8', 'nombre': 'Koke', 'posicion': 'medio', 'poder': 81},
                     {'numero': '10', 'nombre': 'Cardoso', 'posicion': 'medio', 'poder': 80},
                     {'numero': '18', 'nombre': 'G. Simeone', 'posicion': 'medio', 'poder': 81},
                     {'numero': '17', 'nombre': 'De Paul', 'posicion': 'medio', 'poder': 79},
                     {'numero': '22', 'nombre': 'Mendoza', 'posicion': 'medio', 'poder': 71},
                     {'numero': '27', 'nombre': 'Monserrate', 'posicion': 'medio', 'poder': 58},
                     {'numero': '19', 'nombre': 'Almada', 'posicion': 'medio', 'poder': 79},
                     {'numero': '24', 'nombre': 'Rayane', 'posicion': 'medio', 'poder': 61},
                     {'numero': '9', 'nombre': 'Julián Álvarez', 'posicion': 'delantero', 'poder': 87},
                     {'numero': '11', 'nombre': 'Sørloth', 'posicion': 'delantero', 'poder': 83},
                     {'numero': '15', 'nombre': 'Lookman', 'posicion': 'delantero', 'poder': 83},
                     {'numero': '16', 'nombre': 'Álex Baena', 'posicion': 'delantero', 'poder': 83},
                     {'numero': '25', 'nombre': 'N. González', 'posicion': 'delantero', 'poder': 79}],
 'Betis': [{'numero': '1', 'nombre': 'Valles', 'posicion': 'portero', 'poder': 78},
           {'numero': '13', 'nombre': 'Pau López', 'posicion': 'portero', 'poder': 78},
           {'numero': '25', 'nombre': 'Adrián', 'posicion': 'portero', 'poder': 72},
           {'numero': '30', 'nombre': 'Ó. González', 'posicion': 'portero', 'poder': 62},
           {'numero': '16', 'nombre': 'Gavin', 'posicion': 'portero', 'poder': 57},
           {'numero': '5', 'nombre': 'Bartra', 'posicion': 'defensa', 'poder': 79},
           {'numero': '4', 'nombre': 'Natan', 'posicion': 'defensa', 'poder': 79},
           {'numero': '24', 'nombre': 'Ruibal', 'posicion': 'defensa', 'poder': 77},
           {'numero': '23', 'nombre': 'Llorente', 'posicion': 'defensa', 'poder': 76},
           {'numero': '3', 'nombre': 'Junior Firpo', 'posicion': 'defensa', 'poder': 75},
           {'numero': '40', 'nombre': 'Á. Ortiz', 'posicion': 'defensa', 'poder': 70},
           {'numero': '2', 'nombre': 'Chimy', 'posicion': 'defensa', 'poder': 73},
           {'numero': '22', 'nombre': 'Isco', 'posicion': 'medio', 'poder': 84},
           {'numero': '15', 'nombre': 'Lo Celso', 'posicion': 'medio', 'poder': 81},
           {'numero': '8', 'nombre': 'Fornals', 'posicion': 'medio', 'poder': 81},
           {'numero': '7', 'nombre': 'Antony', 'posicion': 'medio', 'poder': 81},
           {'numero': '17', 'nombre': 'Fidalgo', 'posicion': 'medio', 'poder': 78},
           {'numero': '21', 'nombre': 'M. Roca', 'posicion': 'medio', 'poder': 78},
           {'numero': '6', 'nombre': 'Altimira', 'posicion': 'medio', 'poder': 77},
           {'numero': '14', 'nombre': 'Amrabat', 'posicion': 'medio', 'poder': 79},
           {'numero': '18', 'nombre': 'Deossa', 'posicion': 'medio', 'poder': 76},
           {'numero': '10', 'nombre': 'Riquelme', 'posicion': 'medio', 'poder': 59},
           {'numero': '11', 'nombre': 'Corralejo', 'posicion': 'medio', 'poder': 59},
           {'numero': '20', 'nombre': 'D. Pérez', 'posicion': 'medio', 'poder': 63},
           {'numero': '19', 'nombre': 'Cucho', 'posicion': 'delantero', 'poder': 79},
           {'numero': '9', 'nombre': 'Abde', 'posicion': 'delantero', 'poder': 79},
           {'numero': '26', 'nombre': 'P. García', 'posicion': 'delantero', 'poder': 70},
           {'numero': '28', 'nombre': 'V. Gómez', 'posicion': 'delantero', 'poder': 76}],
 'Real Sociedad': [{'numero': '1', 'nombre': 'Remiro', 'posicion': 'portero', 'poder': 82},
                   {'numero': '13', 'nombre': 'U. Marrero', 'posicion': 'portero', 'poder': 69},
                   {'numero': '5', 'nombre': 'Zubeldia', 'posicion': 'defensa', 'poder': 77},
                   {'numero': '31', 'nombre': 'Jon Martín', 'posicion': 'defensa', 'poder': 75},
                   {'numero': '6', 'nombre': 'Elustondo', 'posicion': 'defensa', 'poder': 74},
                   {'numero': '16', 'nombre': 'Ćaleta-Car', 'posicion': 'defensa', 'poder': 74},
                   {'numero': '20', 'nombre': 'Odriozola', 'posicion': 'defensa', 'poder': 73},
                   {'numero': '2', 'nombre': 'Jon Aramburu', 'posicion': 'defensa', 'poder': 77},
                   {'numero': '3', 'nombre': 'S. Gómez', 'posicion': 'defensa', 'poder': 79},
                   {'numero': '17', 'nombre': 'Brais Méndez', 'posicion': 'medio', 'poder': 80},
                   {'numero': '14', 'nombre': 'Kubo', 'posicion': 'medio', 'poder': 81},
                   {'numero': '21', 'nombre': 'Zakharyan', 'posicion': 'medio', 'poder': 73},
                   {'numero': '4', 'nombre': 'Gorrotxa', 'posicion': 'medio', 'poder': 75},
                   {'numero': '12', 'nombre': 'Y. Herrera', 'posicion': 'medio', 'poder': 81},
                   {'numero': '8', 'nombre': 'Turrientes', 'posicion': 'medio', 'poder': 73},
                   {'numero': '11', 'nombre': 'Guedes', 'posicion': 'medio', 'poder': 75},
                   {'numero': '18', 'nombre': 'C. Soler', 'posicion': 'medio', 'poder': 77},
                   {'numero': '24', 'nombre': 'Sučić', 'posicion': 'medio', 'poder': 75},
                   {'numero': '15', 'nombre': 'P. Marín', 'posicion': 'medio', 'poder': 73},
                   {'numero': '22', 'nombre': 'Wesley', 'posicion': 'medio', 'poder': 69},
                   {'numero': '10', 'nombre': 'Oyarzabal', 'posicion': 'delantero', 'poder': 82},
                   {'numero': '7', 'nombre': 'Barrenetxea', 'posicion': 'delantero', 'poder': 78},
                   {'numero': '9', 'nombre': 'Óskarsson', 'posicion': 'delantero', 'poder': 74},
                   {'numero': '19', 'nombre': 'Karrikaburu', 'posicion': 'delantero', 'poder': 67}],
 'Sevilla': [{'numero': '1', 'nombre': 'Vlachodimos', 'posicion': 'portero', 'poder': 78},
             {'numero': '13', 'nombre': 'Nyland', 'posicion': 'portero', 'poder': 75},
             {'numero': '25', 'nombre': 'A. Flores', 'posicion': 'portero', 'poder': 65},
             {'numero': '30', 'nombre': 'R. Romero', 'posicion': 'portero', 'poder': 62},
             {'numero': '3', 'nombre': 'Azpilicueta', 'posicion': 'defensa', 'poder': 78},
             {'numero': '22', 'nombre': 'Gudelj', 'posicion': 'defensa', 'poder': 76},
             {'numero': '15', 'nombre': 'Babá Mendy', 'posicion': 'defensa', 'poder': 76},
             {'numero': '4', 'nombre': 'Kike Salas', 'posicion': 'defensa', 'poder': 75},
             {'numero': '12', 'nombre': 'Suazo', 'posicion': 'defensa', 'poder': 75},
             {'numero': '16', 'nombre': 'Juanlu', 'posicion': 'defensa', 'poder': 75},
             {'numero': '23', 'nombre': 'Marcão', 'posicion': 'defensa', 'poder': 74},
             {'numero': '5', 'nombre': 'Nianzou', 'posicion': 'defensa', 'poder': 72},
             {'numero': '18', 'nombre': 'Castrín', 'posicion': 'defensa', 'poder': 67},
             {'numero': '6', 'nombre': 'Agoumé', 'posicion': 'medio', 'poder': 75},
             {'numero': '17', 'nombre': 'D. Sow', 'posicion': 'medio', 'poder': 76},
             {'numero': '8', 'nombre': 'Joan Jordán', 'posicion': 'medio', 'poder': 74},
             {'numero': '19', 'nombre': 'Cardoso', 'posicion': 'medio', 'poder': 74},
             {'numero': '24', 'nombre': 'Januzaj', 'posicion': 'medio', 'poder': 74},
             {'numero': '10', 'nombre': 'Peque', 'posicion': 'medio', 'poder': 74},
             {'numero': '11', 'nombre': 'Carmona', 'posicion': 'medio', 'poder': 77},
             {'numero': '20', 'nombre': 'Sierra', 'posicion': 'medio', 'poder': 64},
             {'numero': '21', 'nombre': 'Bueno', 'posicion': 'medio', 'poder': 65},
             {'numero': '22', 'nombre': 'Altozano', 'posicion': 'medio', 'poder': 58},
             {'numero': '7', 'nombre': 'R. Vargas', 'posicion': 'delantero', 'poder': 78},
             {'numero': '9', 'nombre': 'Ejuke', 'posicion': 'delantero', 'poder': 77},
             {'numero': '14', 'nombre': 'Á. Sánchez', 'posicion': 'delantero', 'poder': 76},
             {'numero': '28', 'nombre': 'Maupay', 'posicion': 'delantero', 'poder': 74},
             {'numero': '26', 'nombre': 'Akor Adams', 'posicion': 'delantero', 'poder': 74},
             {'numero': '15', 'nombre': 'Isaac Romero', 'posicion': 'delantero', 'poder': 74},
             {'numero': '29', 'nombre': 'Gattoni', 'posicion': 'delantero', 'poder': 71}],
 'Villarreal': [{'numero': '1', 'nombre': 'Luís Júnior', 'posicion': 'portero', 'poder': 78},
                {'numero': '13', 'nombre': 'Tenas', 'posicion': 'portero', 'poder': 75},
                {'numero': '25', 'nombre': 'Conde', 'posicion': 'portero', 'poder': 76},
                {'numero': '30', 'nombre': 'R. Gómez', 'posicion': 'portero', 'poder': 63},
                {'numero': '12', 'nombre': 'R. Veiga', 'posicion': 'defensa', 'poder': 77},
                {'numero': '23', 'nombre': 'Cardona', 'posicion': 'defensa', 'poder': 79},
                {'numero': '26', 'nombre': 'Pau Navarro', 'posicion': 'defensa', 'poder': 69},
                {'numero': '24', 'nombre': 'Pedraza', 'posicion': 'defensa', 'poder': 76},
                {'numero': '2', 'nombre': 'Logan Costa', 'posicion': 'defensa', 'poder': 77},
                {'numero': '15', 'nombre': 'Mouriño', 'posicion': 'defensa', 'poder': 78},
                {'numero': '4', 'nombre': 'Rafa Marín', 'posicion': 'defensa', 'poder': 76},
                {'numero': '5', 'nombre': 'Kambwala', 'posicion': 'defensa', 'poder': 72},
                {'numero': '8', 'nombre': 'Foyth', 'posicion': 'defensa', 'poder': 79},
                {'numero': '14', 'nombre': 'Cabanes', 'posicion': 'defensa', 'poder': 65},
                {'numero': '18', 'nombre': 'P. Gueye', 'posicion': 'medio', 'poder': 79},
                {'numero': '11', 'nombre': 'Comesaña', 'posicion': 'medio', 'poder': 78},
                {'numero': '10', 'nombre': 'Moleiro', 'posicion': 'medio', 'poder': 81},
                {'numero': '17', 'nombre': 'Buchanan', 'posicion': 'medio', 'poder': 75},
                {'numero': '16', 'nombre': 'Partey', 'posicion': 'medio', 'poder': 80},
                {'numero': '6', 'nombre': 'Maciá', 'posicion': 'medio', 'poder': 62},
                {'numero': '9', 'nombre': 'H. López', 'posicion': 'medio', 'poder': 60},
                {'numero': '22', 'nombre': 'Diatta', 'posicion': 'medio', 'poder': 62},
                {'numero': '7', 'nombre': 'Gerard Moreno', 'posicion': 'delantero', 'poder': 81},
                {'numero': '27', 'nombre': 'Ayoze', 'posicion': 'delantero', 'poder': 82},
                {'numero': '19', 'nombre': 'Pépé', 'posicion': 'delantero', 'poder': 81},
                {'numero': '21', 'nombre': 'Oluwaseyi', 'posicion': 'delantero', 'poder': 70},
                {'numero': '28', 'nombre': 'Mikautadze', 'posicion': 'delantero', 'poder': 78},
                {'numero': '20', 'nombre': 'Freeman', 'posicion': 'delantero', 'poder': 73},
                {'numero': '33', 'nombre': 'J.Y. Valou', 'posicion': 'delantero', 'poder': 62},
                {'numero': '29', 'nombre': 'Alfon', 'posicion': 'delantero', 'poder': 75}],
 'Espanyol': [{'numero': '1', 'nombre': 'Dmitrović', 'posicion': 'portero', 'poder': 80},
              {'numero': '13', 'nombre': 'Fortuño', 'posicion': 'portero', 'poder': 65},
              {'numero': '25', 'nombre': 'Tristán', 'posicion': 'portero', 'poder': 64},
              {'numero': '3', 'nombre': 'L. Cabrera', 'posicion': 'defensa', 'poder': 79},
              {'numero': '5', 'nombre': 'C. Romero', 'posicion': 'defensa', 'poder': 78},
              {'numero': '2', 'nombre': 'El Hilali', 'posicion': 'defensa', 'poder': 77},
              {'numero': '23', 'nombre': 'Calero', 'posicion': 'defensa', 'poder': 75},
              {'numero': '6', 'nombre': 'Riedel', 'posicion': 'defensa', 'poder': 72},
              {'numero': '15', 'nombre': 'M. Rubio', 'posicion': 'defensa', 'poder': 70},
              {'numero': '18', 'nombre': 'Salinas', 'posicion': 'defensa', 'poder': 72},
              {'numero': '10', 'nombre': 'Edu Expósito', 'posicion': 'medio', 'poder': 78},
              {'numero': '8', 'nombre': 'P. Lozano', 'posicion': 'medio', 'poder': 76},
              {'numero': '11', 'nombre': 'P. Milla', 'posicion': 'medio', 'poder': 76},
              {'numero': '14', 'nombre': 'U. González', 'posicion': 'medio', 'poder': 75},
              {'numero': '7', 'nombre': 'T. Dolan', 'posicion': 'medio', 'poder': 75},
              {'numero': '4', 'nombre': 'Terrats', 'posicion': 'medio', 'poder': 75},
              {'numero': '17', 'nombre': 'Jofre', 'posicion': 'medio', 'poder': 74},
              {'numero': '20', 'nombre': 'A. Roca', 'posicion': 'medio', 'poder': 73},
              {'numero': '22', 'nombre': 'Noonge', 'posicion': 'medio', 'poder': 72},
              {'numero': '21', 'nombre': 'R. Sánchez', 'posicion': 'medio', 'poder': 70},
              {'numero': '19', 'nombre': 'Pickel', 'posicion': 'medio', 'poder': 71},
              {'numero': '24', 'nombre': 'Puado', 'posicion': 'medio', 'poder': 77},
              {'numero': '9', 'nombre': 'R. Fernández', 'posicion': 'delantero', 'poder': 75}],
 'Getafe': [{'numero': '1', 'nombre': 'David Soria', 'posicion': 'portero', 'poder': 80},
            {'numero': '13', 'nombre': 'Letáček', 'posicion': 'portero', 'poder': 69},
            {'numero': '25', 'nombre': 'J. Benito', 'posicion': 'portero', 'poder': 58},
            {'numero': '31', 'nombre': 'J. Pérez', 'posicion': 'portero', 'poder': 56},
            {'numero': '21', 'nombre': 'Femenía', 'posicion': 'defensa', 'poder': 74},
            {'numero': '3', 'nombre': 'Djené', 'posicion': 'defensa', 'poder': 77},
            {'numero': '22', 'nombre': 'D. Duarte', 'posicion': 'defensa', 'poder': 74},
            {'numero': '4', 'nombre': 'Z. Romero', 'posicion': 'defensa', 'poder': 72},
            {'numero': '2', 'nombre': 'D. Rico', 'posicion': 'defensa', 'poder': 77},
            {'numero': '6', 'nombre': 'Abqar', 'posicion': 'defensa', 'poder': 74},
            {'numero': '26', 'nombre': 'Boselli', 'posicion': 'defensa', 'poder': 72},
            {'numero': '23', 'nombre': 'J. Iglesias', 'posicion': 'defensa', 'poder': 74},
            {'numero': '28', 'nombre': 'Davinchi', 'posicion': 'defensa', 'poder': 67},
            {'numero': '27', 'nombre': 'Mayoral', 'posicion': 'defensa', 'poder': 77},
            {'numero': '8', 'nombre': 'Arambarri', 'posicion': 'medio', 'poder': 80},
            {'numero': '5', 'nombre': 'Luis Milla', 'posicion': 'medio', 'poder': 81},
            {'numero': '10', 'nombre': 'M. Martín', 'posicion': 'medio', 'poder': 72},
            {'numero': '14', 'nombre': 'J. Muñoz', 'posicion': 'medio', 'poder': 74},
            {'numero': '17', 'nombre': 'Sancris', 'posicion': 'medio', 'poder': 73},
            {'numero': '20', 'nombre': 'Nvom', 'posicion': 'medio', 'poder': 71},
            {'numero': '16', 'nombre': 'Birmančević', 'posicion': 'medio', 'poder': 77},
            {'numero': '9', 'nombre': 'Mestanza', 'posicion': 'medio', 'poder': 59},
            {'numero': '11', 'nombre': 'Risco', 'posicion': 'medio', 'poder': 62},
            {'numero': '12', 'nombre': 'J. Montes', 'posicion': 'medio', 'poder': 57},
            {'numero': '29', 'nombre': 'Kamara', 'posicion': 'medio', 'poder': 68},
            {'numero': '24', 'nombre': 'Solozábal', 'posicion': 'medio', 'poder': 59},
            {'numero': '18', 'nombre': 'Bekhoucha', 'posicion': 'medio', 'poder': 64},
            {'numero': '7', 'nombre': 'Satriano', 'posicion': 'delantero', 'poder': 74},
            {'numero': '15', 'nombre': 'L. Vázquez', 'posicion': 'delantero', 'poder': 70},
            {'numero': '19', 'nombre': 'A. Liso', 'posicion': 'delantero', 'poder': 72},
            {'numero': '30', 'nombre': 'Juanmi', 'posicion': 'delantero', 'poder': 73}],
 'Albacete BP': [{'numero': '1', 'nombre': 'Mariño', 'posicion': 'portero', 'poder': 67},
                 {'numero': '13', 'nombre': 'Lizoain', 'posicion': 'portero', 'poder': 69},
                 {'numero': '25', 'nombre': 'M. Ramos', 'posicion': 'portero', 'poder': 58},
                 {'numero': '21', 'nombre': 'C. Neva', 'posicion': 'defensa', 'poder': 71},
                 {'numero': '23', 'nombre': 'P. Sánchez', 'posicion': 'defensa', 'poder': 68},
                 {'numero': '22', 'nombre': 'L. López', 'posicion': 'defensa', 'poder': 68},
                 {'numero': '24', 'nombre': 'Vallejo', 'posicion': 'defensa', 'poder': 72},
                 {'numero': '5', 'nombre': 'J. Moreno', 'posicion': 'defensa', 'poder': 64},
                 {'numero': '2', 'nombre': 'Lorenzo', 'posicion': 'defensa', 'poder': 64},
                 {'numero': '15', 'nombre': 'J. Germán', 'posicion': 'defensa', 'poder': 64},
                 {'numero': '16', 'nombre': 'F. Gámez', 'posicion': 'defensa', 'poder': 69},
                 {'numero': '3', 'nombre': 'Bernabéu', 'posicion': 'defensa', 'poder': 60},
                 {'numero': '14', 'nombre': 'Jota', 'posicion': 'defensa', 'poder': 59},
                 {'numero': '26', 'nombre': 'Á. Rubio', 'posicion': 'defensa', 'poder': 65},
                 {'numero': '4', 'nombre': 'Agus Medina', 'posicion': 'medio', 'poder': 71},
                 {'numero': '8', 'nombre': 'Pacheco', 'posicion': 'medio', 'poder': 64},
                 {'numero': '6', 'nombre': 'Meléndez', 'posicion': 'medio', 'poder': 65},
                 {'numero': '12', 'nombre': 'Cedeño', 'posicion': 'medio', 'poder': 66},
                 {'numero': '17', 'nombre': 'M. Fernández', 'posicion': 'medio', 'poder': 69},
                 {'numero': '9', 'nombre': 'Obeng', 'posicion': 'medio', 'poder': 67},
                 {'numero': '11', 'nombre': 'J. Villar', 'posicion': 'medio', 'poder': 65},
                 {'numero': '7', 'nombre': 'Valverde', 'posicion': 'medio', 'poder': 65},
                 {'numero': '20', 'nombre': 'Capi', 'posicion': 'medio', 'poder': 61},
                 {'numero': '10', 'nombre': 'Bartolomé', 'posicion': 'medio', 'poder': 65},
                 {'numero': '29', 'nombre': 'Morientes', 'posicion': 'medio', 'poder': 58},
                 {'numero': '27', 'nombre': 'Puertas', 'posicion': 'delantero', 'poder': 72},
                 {'numero': '18', 'nombre': 'Jefté', 'posicion': 'delantero', 'poder': 70},
                 {'numero': '19', 'nombre': 'Higinio', 'posicion': 'delantero', 'poder': 68},
                 {'numero': '28', 'nombre': 'Lazo', 'posicion': 'delantero', 'poder': 68}],
 'Celta': [{'numero': '1', 'nombre': 'Iván Villar', 'posicion': 'portero', 'poder': 78},
           {'numero': '13', 'nombre': 'Andrei Radu', 'posicion': 'portero', 'poder': 76},
           {'numero': '30', 'nombre': 'M. Vidal', 'posicion': 'portero', 'poder': 75},
           {'numero': '25', 'nombre': 'El-Abdellaoui', 'posicion': 'portero', 'poder': 72},
           {'numero': '22', 'nombre': 'Á. Núñez', 'posicion': 'defensa', 'poder': 76},
           {'numero': '4', 'nombre': 'Jutglà', 'posicion': 'defensa', 'poder': 76},
           {'numero': '26', 'nombre': 'Aidoo', 'posicion': 'defensa', 'poder': 76},
           {'numero': '2', 'nombre': 'Carreira', 'posicion': 'defensa', 'poder': 75},
           {'numero': '3', 'nombre': 'Marcos Alonso', 'posicion': 'defensa', 'poder': 79},
           {'numero': '5', 'nombre': 'Starfelt', 'posicion': 'defensa', 'poder': 78},
           {'numero': '6', 'nombre': 'J. Rodríguez', 'posicion': 'defensa', 'poder': 76},
           {'numero': '28', 'nombre': 'Durán', 'posicion': 'defensa', 'poder': 74},
           {'numero': '33', 'nombre': 'Domínguez', 'posicion': 'defensa', 'poder': 73},
           {'numero': '27', 'nombre': 'Y. Lago', 'posicion': 'defensa', 'poder': 71},
           {'numero': '12', 'nombre': 'Ristić', 'posicion': 'defensa', 'poder': 73},
           {'numero': '21', 'nombre': 'M. Fernández', 'posicion': 'defensa', 'poder': 70},
           {'numero': '18', 'nombre': 'H. Álvarez', 'posicion': 'medio', 'poder': 75},
           {'numero': '15', 'nombre': 'Vecino', 'posicion': 'medio', 'poder': 76},
           {'numero': '20', 'nombre': 'Sotelo', 'posicion': 'medio', 'poder': 74},
           {'numero': '7', 'nombre': 'Mingueza', 'posicion': 'medio', 'poder': 80},
           {'numero': '10', 'nombre': 'M. Román', 'posicion': 'medio', 'poder': 72},
           {'numero': '8', 'nombre': 'Moriba', 'posicion': 'medio', 'poder': 76},
           {'numero': '11', 'nombre': 'Swedberg', 'posicion': 'delantero', 'poder': 75},
           {'numero': '9', 'nombre': 'Borja Iglesias', 'posicion': 'delantero', 'poder': 80},
           {'numero': '17', 'nombre': 'F. López', 'posicion': 'delantero', 'poder': 73},
           {'numero': '14', 'nombre': 'Iago Aspas', 'posicion': 'delantero', 'poder': 82}],
 'Osasuna': [{'numero': '1', 'nombre': 'S. Herrera', 'posicion': 'portero', 'poder': 79},
             {'numero': '13', 'nombre': 'A. Fernández', 'posicion': 'portero', 'poder': 77},
             {'numero': '28', 'nombre': 'Stamatakis', 'posicion': 'portero', 'poder': 62},
             {'numero': '22', 'nombre': 'R. García', 'posicion': 'defensa', 'poder': 73},
             {'numero': '5', 'nombre': 'Boyomo', 'posicion': 'defensa', 'poder': 78},
             {'numero': '4', 'nombre': 'Catena', 'posicion': 'defensa', 'poder': 78},
             {'numero': '2', 'nombre': 'Rosier', 'posicion': 'defensa', 'poder': 77},
             {'numero': '3', 'nombre': 'Galán', 'posicion': 'defensa', 'poder': 77},
             {'numero': '23', 'nombre': 'Bretones', 'posicion': 'defensa', 'poder': 75},
             {'numero': '24', 'nombre': 'J. Cruz', 'posicion': 'defensa', 'poder': 73},
             {'numero': '15', 'nombre': 'Herrando', 'posicion': 'defensa', 'poder': 75},
             {'numero': '7', 'nombre': 'V. Muñoz', 'posicion': 'medio', 'poder': 76},
             {'numero': '11', 'nombre': 'R. García', 'posicion': 'medio', 'poder': 78},
             {'numero': '17', 'nombre': 'R. Moro', 'posicion': 'medio', 'poder': 75},
             {'numero': '8', 'nombre': 'Moncayola', 'posicion': 'medio', 'poder': 78},
             {'numero': '6', 'nombre': 'Torró', 'posicion': 'medio', 'poder': 78},
             {'numero': '20', 'nombre': 'Baria', 'posicion': 'medio', 'poder': 73},
             {'numero': '16', 'nombre': 'Í. Muñoz', 'posicion': 'medio', 'poder': 75},
             {'numero': '10', 'nombre': 'Aimar Oroz', 'posicion': 'medio', 'poder': 78},
             {'numero': '27', 'nombre': 'Mauro', 'posicion': 'medio', 'poder': 64},
             {'numero': '29', 'nombre': 'I. Benito', 'posicion': 'medio', 'poder': 71},
             {'numero': '14', 'nombre': 'M. Gómez', 'posicion': 'medio', 'poder': 77},
             {'numero': '9', 'nombre': 'Budimir', 'posicion': 'delantero', 'poder': 81},
             {'numero': '18', 'nombre': 'Arnau', 'posicion': 'delantero', 'poder': 73}],
 'Deportivo Alavés': [{'numero': '1', 'nombre': 'Sivera', 'posicion': 'portero', 'poder': 77},
                      {'numero': '13', 'nombre': 'R. Fernández', 'posicion': 'portero', 'poder': 72},
                      {'numero': '28', 'nombre': 'Swiderski', 'posicion': 'portero', 'poder': 61},
                      {'numero': '23', 'nombre': 'Parada', 'posicion': 'defensa', 'poder': 70},
                      {'numero': '5', 'nombre': 'Garcés', 'posicion': 'defensa', 'poder': 72},
                      {'numero': '24', 'nombre': 'Yusi', 'posicion': 'defensa', 'poder': 68},
                      {'numero': '25', 'nombre': 'Mariano', 'posicion': 'defensa', 'poder': 70},
                      {'numero': '22', 'nombre': 'Diabate', 'posicion': 'defensa', 'poder': 72},
                      {'numero': '26', 'nombre': 'Koski', 'posicion': 'defensa', 'poder': 66},
                      {'numero': '2', 'nombre': 'Tenaglia', 'posicion': 'defensa', 'poder': 77},
                      {'numero': '4', 'nombre': 'Pacheco', 'posicion': 'defensa', 'poder': 74},
                      {'numero': '3', 'nombre': 'Jonny', 'posicion': 'defensa', 'poder': 75},
                      {'numero': '30', 'nombre': 'Mañas', 'posicion': 'defensa', 'poder': 63},
                      {'numero': '29', 'nombre': 'Morcillo', 'posicion': 'defensa', 'poder': 59},
                      {'numero': '10', 'nombre': 'Aleñá', 'posicion': 'medio', 'poder': 74},
                      {'numero': '14', 'nombre': 'D. Suárez', 'posicion': 'medio', 'poder': 74},
                      {'numero': '18', 'nombre': 'Guridi', 'posicion': 'medio', 'poder': 74},
                      {'numero': '19', 'nombre': 'Protesoni', 'posicion': 'medio', 'poder': 73},
                      {'numero': '6', 'nombre': 'P. Ibáñez', 'posicion': 'medio', 'poder': 73},
                      {'numero': '27', 'nombre': 'Á. Pérez', 'posicion': 'medio', 'poder': 64},
                      {'numero': '8', 'nombre': 'A. Blanco', 'posicion': 'medio', 'poder': 75},
                      {'numero': '15', 'nombre': 'Guevara', 'posicion': 'medio', 'poder': 74},
                      {'numero': '17', 'nombre': 'Rebbach', 'posicion': 'medio', 'poder': 72},
                      {'numero': '31', 'nombre': 'Pinillos', 'posicion': 'medio', 'poder': 70},
                      {'numero': '11', 'nombre': 'Calebe', 'posicion': 'medio', 'poder': 71},
                      {'numero': '9', 'nombre': 'Boyé', 'posicion': 'delantero', 'poder': 74},
                      {'numero': '16', 'nombre': 'T. Martínez', 'posicion': 'delantero', 'poder': 75}],
 'Girona': [{'numero': '31', 'nombre': 'ter Stegen', 'posicion': 'portero', 'poder': 85},
            {'numero': '13', 'nombre': 'Gazzaniga', 'posicion': 'portero', 'poder': 78},
            {'numero': '25', 'nombre': 'J. Carlos', 'posicion': 'portero', 'poder': 71},
            {'numero': '30', 'nombre': 'Krapyvtsov', 'posicion': 'portero', 'poder': 64},
            {'numero': '2', 'nombre': 'A. Martínez', 'posicion': 'defensa', 'poder': 78},
            {'numero': '3', 'nombre': 'A. Moreno', 'posicion': 'defensa', 'poder': 77},
            {'numero': '4', 'nombre': 'Blind', 'posicion': 'defensa', 'poder': 76},
            {'numero': '24', 'nombre': 'Witsel', 'posicion': 'defensa', 'poder': 76},
            {'numero': '26', 'nombre': 'D. López', 'posicion': 'defensa', 'poder': 76},
            {'numero': '22', 'nombre': 'Francés', 'posicion': 'defensa', 'poder': 75},
            {'numero': '5', 'nombre': 'V. Reis', 'posicion': 'defensa', 'poder': 73},
            {'numero': '23', 'nombre': 'Rincón', 'posicion': 'defensa', 'poder': 73},
            {'numero': '33', 'nombre': 'Gibi', 'posicion': 'defensa', 'poder': 61},
            {'numero': '28', 'nombre': 'Ounahi', 'posicion': 'medio', 'poder': 78},
            {'numero': '8', 'nombre': 'I. Martín', 'posicion': 'medio', 'poder': 77},
            {'numero': '6', 'nombre': 'Beltrán', 'posicion': 'medio', 'poder': 77},
            {'numero': '10', 'nombre': 'Lemar', 'posicion': 'medio', 'poder': 77},
            {'numero': '7', 'nombre': 'Bryan Gil', 'posicion': 'medio', 'poder': 77},
            {'numero': '16', 'nombre': 'Van de Beek', 'posicion': 'medio', 'poder': 75},
            {'numero': '14', 'nombre': 'Echeverri', 'posicion': 'medio', 'poder': 73},
            {'numero': '20', 'nombre': 'Kourouma', 'posicion': 'medio', 'poder': 65},
            {'numero': '11', 'nombre': 'Tsygankov', 'posicion': 'delantero', 'poder': 78},
            {'numero': '9', 'nombre': 'Vanat', 'posicion': 'delantero', 'poder': 77},
            {'numero': '17', 'nombre': 'Stuani', 'posicion': 'delantero', 'poder': 76},
            {'numero': '18', 'nombre': 'Portu', 'posicion': 'delantero', 'poder': 75},
            {'numero': '15', 'nombre': 'J. Roca', 'posicion': 'delantero', 'poder': 72},
            {'numero': '27', 'nombre': 'A. Ruiz', 'posicion': 'delantero', 'poder': 72},
            {'numero': '29', 'nombre': 'Dame Ba', 'posicion': 'delantero', 'poder': 62},
            {'numero': '21', 'nombre': 'J. Arango', 'posicion': 'delantero', 'poder': 61}],
 'Real Oviedo': [{'numero': '1', 'nombre': 'Escandell', 'posicion': 'portero', 'poder': 78},
                 {'numero': '13', 'nombre': 'Moldovan', 'posicion': 'portero', 'poder': 71},
                 {'numero': '32', 'nombre': 'Narváez', 'posicion': 'portero', 'poder': 63},
                 {'numero': '2', 'nombre': 'N. Vidal', 'posicion': 'defensa', 'poder': 72},
                 {'numero': '3', 'nombre': 'J. López', 'posicion': 'defensa', 'poder': 72},
                 {'numero': '4', 'nombre': 'D. Carmo', 'posicion': 'defensa', 'poder': 75},
                 {'numero': '5', 'nombre': 'Costas', 'posicion': 'defensa', 'poder': 74},
                 {'numero': '22', 'nombre': 'Borbas', 'posicion': 'defensa', 'poder': 72},
                 {'numero': '23', 'nombre': 'Bailly', 'posicion': 'defensa', 'poder': 73},
                 {'numero': '24', 'nombre': 'D. Calvo', 'posicion': 'defensa', 'poder': 72},
                 {'numero': '25', 'nombre': 'Alhassane', 'posicion': 'defensa', 'poder': 71},
                 {'numero': '26', 'nombre': 'Forés', 'posicion': 'defensa', 'poder': 70},
                 {'numero': '31', 'nombre': 'M. Esteban', 'posicion': 'defensa', 'poder': 64},
                 {'numero': '6', 'nombre': 'Colombatto', 'posicion': 'medio', 'poder': 73},
                 {'numero': '8', 'nombre': 'Sibo', 'posicion': 'medio', 'poder': 68},
                 {'numero': '10', 'nombre': 'A. Reina', 'posicion': 'medio', 'poder': 73},
                 {'numero': '7', 'nombre': 'Chairá', 'posicion': 'medio', 'poder': 72},
                 {'numero': '11', 'nombre': 'H. Hassan', 'posicion': 'medio', 'poder': 74},
                 {'numero': '14', 'nombre': 'Cazorla', 'posicion': 'medio', 'poder': 75},
                 {'numero': '17', 'nombre': 'T. Fernández', 'posicion': 'medio', 'poder': 74},
                 {'numero': '16', 'nombre': 'Ahiado', 'posicion': 'medio', 'poder': 68},
                 {'numero': '18', 'nombre': 'Dendoncker', 'posicion': 'medio', 'poder': 74},
                 {'numero': '19', 'nombre': 'Fonseca', 'posicion': 'medio', 'poder': 73},
                 {'numero': '27', 'nombre': 'Ilić', 'posicion': 'medio', 'poder': 69},
                 {'numero': '28', 'nombre': 'Ejaria', 'posicion': 'medio', 'poder': 66},
                 {'numero': '30', 'nombre': 'Agudín', 'posicion': 'medio', 'poder': 63},
                 {'numero': '9', 'nombre': 'F. Viñas', 'posicion': 'delantero', 'poder': 72}],
 'Levante': [{'numero': '1', 'nombre': 'M. Ryan', 'posicion': 'portero', 'poder': 79},
             {'numero': '13', 'nombre': 'Campos', 'posicion': 'portero', 'poder': 69},
             {'numero': '30', 'nombre': 'Primo', 'posicion': 'portero', 'poder': 60},
             {'numero': '2', 'nombre': 'Toljan', 'posicion': 'defensa', 'poder': 74},
             {'numero': '3', 'nombre': 'M. Sánchez', 'posicion': 'defensa', 'poder': 75},
             {'numero': '4', 'nombre': 'M. Moreno', 'posicion': 'defensa', 'poder': 70},
             {'numero': '5', 'nombre': 'Dela', 'posicion': 'defensa', 'poder': 73},
             {'numero': '23', 'nombre': 'Floezabal', 'posicion': 'defensa', 'poder': 71},
             {'numero': '24', 'nombre': 'Matturro', 'posicion': 'defensa', 'poder': 68},
             {'numero': '25', 'nombre': 'Morales', 'posicion': 'defensa', 'poder': 74},
             {'numero': '19', 'nombre': 'Pampín', 'posicion': 'defensa', 'poder': 69},
             {'numero': '26', 'nombre': 'Espí', 'posicion': 'defensa', 'poder': 68},
             {'numero': '31', 'nombre': 'N. Pérez', 'posicion': 'defensa', 'poder': 63},
             {'numero': '33', 'nombre': 'Brugui', 'posicion': 'defensa', 'poder': 73},
             {'numero': '6', 'nombre': 'P. Martínez', 'posicion': 'medio', 'poder': 74},
             {'numero': '8', 'nombre': 'Raghouber', 'posicion': 'medio', 'poder': 69},
             {'numero': '10', 'nombre': 'C. Álvarez', 'posicion': 'medio', 'poder': 77},
             {'numero': '7', 'nombre': 'I. Romero', 'posicion': 'medio', 'poder': 74},
             {'numero': '11', 'nombre': 'Tunde', 'posicion': 'medio', 'poder': 66},
             {'numero': '22', 'nombre': 'Arriaga', 'posicion': 'medio', 'poder': 74},
             {'numero': '14', 'nombre': 'Olasagasti', 'posicion': 'medio', 'poder': 73},
             {'numero': '15', 'nombre': 'Vencedor', 'posicion': 'medio', 'poder': 72},
             {'numero': '17', 'nombre': 'Losada', 'posicion': 'medio', 'poder': 71},
             {'numero': '16', 'nombre': 'V. García', 'posicion': 'medio', 'poder': 70},
             {'numero': '27', 'nombre': 'O. Rey', 'posicion': 'medio', 'poder': 73},
             {'numero': '28', 'nombre': 'Abed', 'posicion': 'medio', 'poder': 65},
             {'numero': '9', 'nombre': 'K. Edouard', 'posicion': 'delantero', 'poder': 74},
             {'numero': '32', 'nombre': 'P. Cortés', 'posicion': 'delantero', 'poder': 66}],
 'Mallorca': [{'numero': '1', 'nombre': 'Leo Román', 'posicion': 'portero', 'poder': 77},
              {'numero': '20', 'nombre': 'Bergström', 'posicion': 'portero', 'poder': 67},
              {'numero': '32', 'nombre': 'Cuéllar', 'posicion': 'portero', 'poder': 67},
              {'numero': '3', 'nombre': 'Mojica', 'posicion': 'defensa', 'poder': 78},
              {'numero': '4', 'nombre': 'Raillo', 'posicion': 'defensa', 'poder': 80},
              {'numero': '5', 'nombre': 'Valjent', 'posicion': 'defensa', 'poder': 77},
              {'numero': '22', 'nombre': 'Maffeo', 'posicion': 'defensa', 'poder': 78},
              {'numero': '2', 'nombre': 'Kumbulla', 'posicion': 'defensa', 'poder': 77},
              {'numero': '19', 'nombre': 'Morev', 'posicion': 'defensa', 'poder': 73},
              {'numero': '16', 'nombre': 'T. Lato', 'posicion': 'defensa', 'poder': 73},
              {'numero': '30', 'nombre': 'D. López', 'posicion': 'defensa', 'poder': 68},
              {'numero': '25', 'nombre': 'Salhi', 'posicion': 'defensa', 'poder': 60},
              {'numero': '28', 'nombre': 'Á. Prats', 'posicion': 'defensa', 'poder': 72},
              {'numero': '8', 'nombre': 'Mascarell', 'posicion': 'medio', 'poder': 75},
              {'numero': '6', 'nombre': 'Samú Costa', 'posicion': 'medio', 'poder': 78},
              {'numero': '11', 'nombre': 'Virgilí', 'posicion': 'medio', 'poder': 75},
              {'numero': '10', 'nombre': 'Darder', 'posicion': 'medio', 'poder': 80},
              {'numero': '21', 'nombre': 'M. Joseph', 'posicion': 'medio', 'poder': 72},
              {'numero': '7', 'nombre': 'Morlanes', 'posicion': 'medio', 'poder': 77},
              {'numero': '14', 'nombre': 'Asano', 'posicion': 'medio', 'poder': 74},
              {'numero': '17', 'nombre': 'Pablo Torre', 'posicion': 'medio', 'poder': 74},
              {'numero': '23', 'nombre': 'A. Sánchez', 'posicion': 'medio', 'poder': 73},
              {'numero': '29', 'nombre': 'Salas', 'posicion': 'medio', 'poder': 62},
              {'numero': '31', 'nombre': 'Kalumba', 'posicion': 'medio', 'poder': 65},
              {'numero': '27', 'nombre': 'Llabrés', 'posicion': 'medio', 'poder': 69},
              {'numero': '9', 'nombre': 'Muriqi', 'posicion': 'delantero', 'poder': 80},
              {'numero': '24', 'nombre': 'Luvumbo', 'posicion': 'delantero', 'poder': 70}],
 'Elche': [{'numero': '1', 'nombre': 'Iván Peña', 'posicion': 'portero', 'poder': 77},
           {'numero': '12', 'nombre': 'Dituro', 'posicion': 'portero', 'poder': 75},
           {'numero': '31', 'nombre': 'Iturbe', 'posicion': 'portero', 'poder': 66},
           {'numero': '5', 'nombre': 'Bigas', 'posicion': 'defensa', 'poder': 76},
           {'numero': '4', 'nombre': 'Affengruber', 'posicion': 'defensa', 'poder': 76},
           {'numero': '3', 'nombre': 'V. Chust', 'posicion': 'defensa', 'poder': 73},
           {'numero': '17', 'nombre': 'Ceneda', 'posicion': 'defensa', 'poder': 72},
           {'numero': '2', 'nombre': 'Pedrosa', 'posicion': 'defensa', 'poder': 75},
           {'numero': '22', 'nombre': 'Pétrot', 'posicion': 'defensa', 'poder': 70},
           {'numero': '20', 'nombre': 'Donald', 'posicion': 'defensa', 'poder': 69},
           {'numero': '26', 'nombre': 'Boayar', 'posicion': 'defensa', 'poder': 62},
           {'numero': '27', 'nombre': 'Albert', 'posicion': 'defensa', 'poder': 58},
           {'numero': '29', 'nombre': 'Sangaré', 'posicion': 'defensa', 'poder': 63},
           {'numero': '32', 'nombre': 'H. Fort', 'posicion': 'defensa', 'poder': 71},
           {'numero': '6', 'nombre': 'M. Aguado', 'posicion': 'medio', 'poder': 73},
           {'numero': '11', 'nombre': 'Valera', 'posicion': 'medio', 'poder': 75},
           {'numero': '8', 'nombre': 'Álex Febas', 'posicion': 'medio', 'poder': 78},
           {'numero': '10', 'nombre': 'M. Neto', 'posicion': 'medio', 'poder': 72},
           {'numero': '21', 'nombre': 'Josan', 'posicion': 'medio', 'poder': 72},
           {'numero': '14', 'nombre': 'G. Villar', 'posicion': 'medio', 'poder': 72},
           {'numero': '15', 'nombre': 'Yaw Santiago', 'posicion': 'medio', 'poder': 70},
           {'numero': '19', 'nombre': 'Diangana', 'posicion': 'medio', 'poder': 70},
           {'numero': '24', 'nombre': 'F. Redondo', 'posicion': 'medio', 'poder': 70},
           {'numero': '28', 'nombre': 'Tete Morente', 'posicion': 'medio', 'poder': 71},
           {'numero': '30', 'nombre': 'Á. Sánchez', 'posicion': 'medio', 'poder': 62},
           {'numero': '25', 'nombre': 'A. Martínez', 'posicion': 'medio', 'poder': 59},
           {'numero': '9', 'nombre': 'Álex Rodríguez', 'posicion': 'delantero', 'poder': 71},
           {'numero': '7', 'nombre': 'André da Silva', 'posicion': 'delantero', 'poder': 76},
           {'numero': '13', 'nombre': 'Rafa Mir', 'posicion': 'delantero', 'poder': 75}],
 'Valencia': [{'numero': '1', 'nombre': 'Dimitrievski', 'posicion': 'portero', 'poder': 77},
              {'numero': '13', 'nombre': 'C. Rivero', 'posicion': 'portero', 'poder': 65},
              {'numero': '31', 'nombre': 'Agirrezabala', 'posicion': 'portero', 'poder': 77},
              {'numero': '14', 'nombre': 'Gayà', 'posicion': 'defensa', 'poder': 78},
              {'numero': '5', 'nombre': 'Copete', 'posicion': 'defensa', 'poder': 74},
              {'numero': '3', 'nombre': 'C. Tárrega', 'posicion': 'defensa', 'poder': 75},
              {'numero': '4', 'nombre': 'T. Correia', 'posicion': 'defensa', 'poder': 75},
              {'numero': '21', 'nombre': 'J. Vázquez', 'posicion': 'defensa', 'poder': 71},
              {'numero': '25', 'nombre': 'U. Núñez', 'posicion': 'defensa', 'poder': 72},
              {'numero': '20', 'nombre': 'E. Cömert', 'posicion': 'defensa', 'poder': 72},
              {'numero': '27', 'nombre': 'R. Iranzo', 'posicion': 'defensa', 'poder': 64},
              {'numero': '29', 'nombre': 'D. Foulquier', 'posicion': 'defensa', 'poder': 73},
              {'numero': '32', 'nombre': 'M. Diakhaby', 'posicion': 'defensa', 'poder': 76},
              {'numero': '2', 'nombre': 'G. Rodríguez', 'posicion': 'medio', 'poder': 75},
              {'numero': '8', 'nombre': 'Javi Guerra', 'posicion': 'medio', 'poder': 77},
              {'numero': '10', 'nombre': 'A. Almeida', 'posicion': 'medio', 'poder': 74},
              {'numero': '18', 'nombre': 'Pepelu', 'posicion': 'medio', 'poder': 76},
              {'numero': '22', 'nombre': 'Santamaría', 'posicion': 'medio', 'poder': 75},
              {'numero': '23', 'nombre': 'F. Ugriníć', 'posicion': 'medio', 'poder': 74},
              {'numero': '28', 'nombre': 'L. Núñez', 'posicion': 'medio', 'poder': 61},
              {'numero': '30', 'nombre': 'D. Otorbi', 'posicion': 'medio', 'poder': 63},
              {'numero': '9', 'nombre': 'H. Duro', 'posicion': 'delantero', 'poder': 77},
              {'numero': '6', 'nombre': 'U. Sadiq', 'posicion': 'delantero', 'poder': 76},
              {'numero': '7', 'nombre': 'A. Danjuma', 'posicion': 'delantero', 'poder': 75},
              {'numero': '11', 'nombre': 'L. Rioja', 'posicion': 'delantero', 'poder': 77},
              {'numero': '15', 'nombre': 'L. Beltrán', 'posicion': 'delantero', 'poder': 75},
              {'numero': '16', 'nombre': 'D. López', 'posicion': 'delantero', 'poder': 77},
              {'numero': '17', 'nombre': 'Ramazani', 'posicion': 'delantero', 'poder': 74},
              {'numero': '19', 'nombre': 'Dani Raba', 'posicion': 'delantero', 'poder': 75},
              {'numero': '26', 'nombre': 'A. Blázquez', 'posicion': 'delantero', 'poder': 62}],
 'Rayo Vallecano': [{'numero': '1', 'nombre': 'Batalla', 'posicion': 'portero', 'poder': 79},
                    {'numero': '13', 'nombre': 'Cárdenas', 'posicion': 'portero', 'poder': 73},
                    {'numero': '31', 'nombre': 'J. Gil', 'posicion': 'portero', 'poder': 58},
                    {'numero': '32', 'nombre': 'A. Molina', 'posicion': 'portero', 'poder': 54},
                    {'numero': '12', 'nombre': 'Chavarría', 'posicion': 'defensa', 'poder': 78},
                    {'numero': '5', 'nombre': 'N. Mendy', 'posicion': 'defensa', 'poder': 73},
                    {'numero': '4', 'nombre': 'Lejeune', 'posicion': 'defensa', 'poder': 78},
                    {'numero': '23', 'nombre': 'Ratiu', 'posicion': 'defensa', 'poder': 79},
                    {'numero': '3', 'nombre': 'Balliu', 'posicion': 'defensa', 'poder': 75},
                    {'numero': '2', 'nombre': 'Feline', 'posicion': 'defensa', 'poder': 75},
                    {'numero': '17', 'nombre': 'Espino', 'posicion': 'defensa', 'poder': 72},
                    {'numero': '27', 'nombre': 'Vertrouwd', 'posicion': 'defensa', 'poder': 67},
                    {'numero': '33', 'nombre': 'Mumín', 'posicion': 'defensa', 'poder': 77},
                    {'numero': '6', 'nombre': 'U. López', 'posicion': 'medio', 'poder': 76},
                    {'numero': '8', 'nombre': 'P. Ciss', 'posicion': 'medio', 'poder': 78},
                    {'numero': '11', 'nombre': 'Á. García', 'posicion': 'medio', 'poder': 81},
                    {'numero': '10', 'nombre': 'Isi', 'posicion': 'medio', 'poder': 81},
                    {'numero': '7', 'nombre': 'Akhomach', 'posicion': 'medio', 'poder': 74},
                    {'numero': '15', 'nombre': 'Ó. Valentín', 'posicion': 'medio', 'poder': 77},
                    {'numero': '16', 'nombre': 'Gumbau', 'posicion': 'medio', 'poder': 72},
                    {'numero': '18', 'nombre': 'P. Díaz', 'posicion': 'medio', 'poder': 75},
                    {'numero': '26', 'nombre': 'F. Pérez', 'posicion': 'medio', 'poder': 71},
                    {'numero': '28', 'nombre': 'Trejo', 'posicion': 'medio', 'poder': 70},
                    {'numero': '29', 'nombre': 'Becerra', 'posicion': 'medio', 'poder': 60},
                    {'numero': '34', 'nombre': 'D. Méndez', 'posicion': 'medio', 'poder': 64},
                    {'numero': '9', 'nombre': 'D. Frutos', 'posicion': 'delantero', 'poder': 80},
                    {'numero': '14', 'nombre': 'Alemão', 'posicion': 'delantero', 'poder': 73},
                    {'numero': '20', 'nombre': 'C. Martín', 'posicion': 'delantero', 'poder': 69},
                    {'numero': '24', 'nombre': 'Nteka', 'posicion': 'delantero', 'poder': 70},
                    {'numero': '25', 'nombre': 'Camello', 'posicion': 'delantero', 'poder': 72}],
 'Córdoba': [{'numero': '1', 'nombre': 'F. Palatsí', 'posicion': 'portero', 'poder': 75},
             {'numero': '13', 'nombre': 'T. Fernández', 'posicion': 'portero', 'poder': 70},
             {'numero': '2', 'nombre': 'L. Calderón', 'posicion': 'defensa', 'poder': 74},
             {'numero': '5', 'nombre': 'M. Valenzuela', 'posicion': 'defensa', 'poder': 73},
             {'numero': '6', 'nombre': 'P. Gutiérrez', 'posicion': 'defensa', 'poder': 74},
             {'numero': '3', 'nombre': 'A. Baidoo', 'posicion': 'defensa', 'poder': 73},
             {'numero': '22', 'nombre': 'C. Ángel', 'posicion': 'defensa', 'poder': 72},
             {'numero': '14', 'nombre': 'C. Boselli', 'posicion': 'defensa', 'poder': 72},
             {'numero': '23', 'nombre': 'A. Lolo', 'posicion': 'defensa', 'poder': 70},
             {'numero': '4', 'nombre': 'A. Romero', 'posicion': 'medio', 'poder': 75},
             {'numero': '8', 'nombre': 'J. Andrés Prieto', 'posicion': 'medio', 'poder': 74},
             {'numero': '10', 'nombre': 'A. Carvalho', 'posicion': 'medio', 'poder': 76},
             {'numero': '20', 'nombre': 'A. Vallejo', 'posicion': 'medio', 'poder': 74},
             {'numero': '7', 'nombre': 'C. Isidoro', 'posicion': 'medio', 'poder': 74},
             {'numero': '17', 'nombre': 'L. Arezo', 'posicion': 'medio', 'poder': 73},
             {'numero': '11', 'nombre': 'K. Mfulu', 'posicion': 'medio', 'poder': 72},
             {'numero': '16', 'nombre': 'C. Bañuls', 'posicion': 'medio', 'poder': 72},
             {'numero': '9', 'nombre': 'C. Zaldua', 'posicion': 'delantero', 'poder': 76},
             {'numero': '19', 'nombre': 'J. Sebas Moyano', 'posicion': 'delantero', 'poder': 74},
             {'numero': '21', 'nombre': 'A. Cruz', 'posicion': 'delantero', 'poder': 73},
             {'numero': '18', 'nombre': 'D. Casado', 'posicion': 'delantero', 'poder': 72}]}
